apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Demo"
  description: "Description"
  annotations:
    github.com/project-slug: Iesoft-Docsetup
    backstage.io/techdocs-ref: dir.
spec:
  type: documentation
  lifecycle: experimental
  owner: "group:default/iesoft"
